# Generated by Django 3.2 on 2023-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('token', models.CharField(max_length=50)),
                ('plan', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('exp_date', models.DateTimeField(null=True)),
                ('change_count', models.IntegerField(default=3)),
            ],
        ),
    ]
