# Generated by Django 3.2 on 2023-02-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_changed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='changed_date',
        ),
    ]
