# Generated by Django 3.2 on 2023-02-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_changed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='changed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
