# Generated by Django 3.2 on 2023-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_changed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='changed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='exp_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
