# Generated by Django 3.2 on 2023-02-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_change_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='plan',
            new_name='charge',
        ),
    ]
