# Generated by Django 3.2 on 2023-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_plan_users_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_charge_date',
            field=models.DateTimeField(null=True),
        ),
    ]
