# Generated by Django 3.2 on 2023-02-21 11:39

from django.db import migrations, models
import helpers.generator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_users_last_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(default=helpers.generator.Token_Generator, max_length=40, unique=True),
        ),
    ]
