# Generated by Django 3.2 on 2023-02-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_user_id_users_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
