# Generated by Django 3.2 on 2023-03-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='charge',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
