# Generated by Django 3.2 on 2023-03-04 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_changed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='changed_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 9, 4, 59, 530552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 9, 4, 59, 530552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
