# Generated by Django 3.2 on 2023-03-04 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20230304_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='changed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
